; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; Force the FH4R2 board to be the default target if none is chosen
default_envs = esp32-s3-fh4r2

; -------------------------------------------------------------
; SHARED CONFIGURATION (Applies to both boards)
; -------------------------------------------------------------
[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps = 
    adafruit/Adafruit GFX Library @ ^1.12.6
    adafruit/Adafruit ILI9341 @ ^1.6.3

; -------------------------------------------------------------
; ENVIRONMENT 1: ESP32-S3 Zero (N8R8 - 8MB Flash / 8MB OPI PSRAM)
; -------------------------------------------------------------
[env:esp32-s3-zero-n8r8]
board = esp32-s3-devkitm-1
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
build_flags = 
  -DARDUINO_USB_CDC_ON_BOOT=1     ;set to zero on production version so last of serial does not lock it up
  -DARDUINO_USB_MODE=1
  -DBOARD_HAS_PSRAM
  -DCONFIG_SPIRAM_MODE_OCT=1
  -DCONFIG_SPIRAM_SPEED_80M=1

; -------------------------------------------------------------
; ENVIRONMENT 2: ESP32-S3FH4R2 (4MB Flash / 2MB QPI PSRAM)
; -------------------------------------------------------------
[env:esp32-s3-fh4r2]
board = esp32-s3-devkitm-1
board_upload.flash_size = 4MB
board_build.partitions = default.csv
build_flags = 
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DBOARD_HAS_PSRAM

